### ISSUE TITLE
0.14 release checklist

### ISSUE THREAD

**Issue by lo5** [h2oai/nitro#70]
- [x] `bg-ui-*` is not useful in its current form; need to refer to accent, background, foreground shades, e.g. `bg-accent-500`.
- [x] Examples
  - [x] Alerts
  - [x] Pagination
  - [x] Cards
  - [x] Badges
  - [x] Personas
  - [x] CTA
  - [x] Tags
  - [x] Steps
  - [x] Stats
  - [ ] Footer
  - [ ] Review
  - [x] Sections
- [x] Change examples with `box(items=[a,b,c])` to `box(a, b, c)`.
- [x] Livedocs ToC broken - continue button displayed.
- [x] Update cheat sheet
- [x] Rework color variables examples
- [x] Document API changes
- [x] Mark deprecated APIs
- [x] Rework advanced layout examples
- [x] Rework layout examples
- [ ] Dropdown list scrollbars broken
- [x] Webview broken - heights not respected
- [ ] Livedocs ToC hash broken - cannot navigate back
